//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacenes()
        {
            this.Estaciones = new HashSet<Estaciones>();
        }
    
        public short id_Almacenes { get; set; }
        public short id_Empresas_Sucursales { get; set; }
        public string Almacen { get; set; }
        public string Direccion { get; set; }
        public string Teleono { get; set; }
        public string Contacto { get; set; }
        public string Horarios { get; set; }
        public Nullable<bool> esDeposito { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public Nullable<System.DateTime> FechaActual { get; set; }
    
        public virtual Empresas_Sucursales Empresas_Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estaciones> Estaciones { get; set; }
    }
}
