//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bancos()
        {
            this.Facturas_TiposPago = new HashSet<Facturas_TiposPago>();
        }
    
        public short id_Bancos { get; set; }
        public string Cuenta { get; set; }
        public string Nombre { get; set; }
        public string Banco { get; set; }
        public short id_DefTipoCuenta { get; set; }
        public string CGCuenta { get; set; }
        public decimal SaldoActual { get; set; }
        public Nullable<decimal> DepositosDiferidos { get; set; }
        public Nullable<decimal> ChequesPostdatados { get; set; }
        public System.DateTime UltimaActualizacion { get; set; }
        public Nullable<int> ProximoCheque { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_TiposPago> Facturas_TiposPago { get; set; }
    }
}
