//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajas_Egresos
    {
        public short id_Cajas_Egresos { get; set; }
        public Nullable<short> id_ArchivoAsociado { get; set; }
        public long id_Estaciones_Sesiones { get; set; }
        public short id_TiposEgreso_Caja { get; set; }
        public Nullable<long> id_Cajas_Cortes_IF { get; set; }
        public Nullable<short> id_Usuario_Autoriza { get; set; }
        public Nullable<System.DateTime> FechaActural { get; set; }
        public Nullable<System.DateTime> FechaRecibo { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public string NombreEntrega { get; set; }
        public string NombreAsociado { get; set; }
        public string NombreRecibe { get; set; }
        public string nroDocAsociado { get; set; }
        public string nroReciboEgreso { get; set; }
    
        public virtual Cajas_Cortes_IF Cajas_Cortes_IF { get; set; }
        public virtual Estaciones_Sesiones Estaciones_Sesiones { get; set; }
        public virtual TiposEgreso_Caja TiposEgreso_Caja { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
