//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajas_Cortes_IF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cajas_Cortes_IF()
        {
            this.Cajas_Egresos = new HashSet<Cajas_Egresos>();
        }
    
        public long id_Cajas_Cortes_IF { get; set; }
        public long id_Cajas_Cortes { get; set; }
        public string RIF_IF { get; set; }
        public System.DateTime FechaFinal_IF { get; set; }
        public byte[] FechaInicial_IF { get; set; }
        public int nroCorteZ_IF { get; set; }
        public int nroFacturaInicial_IF { get; set; }
        public int nrofacturaFinal_IF { get; set; }
        public string nroSerial_IF { get; set; }
        public decimal MontoTotal1 { get; set; }
        public Nullable<decimal> MontoTotal2 { get; set; }
        public Nullable<decimal> MontoTotal3 { get; set; }
        public decimal TasaIva1 { get; set; }
        public Nullable<decimal> TasaIva2 { get; set; }
        public Nullable<decimal> TasaIva3 { get; set; }
    
        public virtual Cajas_Cortes Cajas_Cortes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cajas_Egresos> Cajas_Egresos { get; set; }
    }
}
