//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public long id_clientes { get; set; }
        public short id_Empresas_Sucursales { get; set; }
        public Nullable<long> id_World_Localidades { get; set; }
        public Nullable<short> id_World_Regiones { get; set; }
        public Nullable<short> id_Ven_Municipios { get; set; }
        public Nullable<short> id_World__Paises { get; set; }
        public Nullable<short> id_Ven_Parroquias { get; set; }
        public Nullable<short> id_World_Profesiones { get; set; }
        public Nullable<short> id_TiposPago { get; set; }
        public string Apellidos { get; set; }
        public string CI { get; set; }
        public string codigoPostal { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public Nullable<bool> esEmpresa { get; set; }
        public string Nombres { get; set; }
        public string Pasaporte { get; set; }
        public string telefono { get; set; }
        public string telefono_movil { get; set; }
    
        public virtual Empresas_Sucursales Empresas_Sucursales { get; set; }
        public virtual TiposPago TiposPago { get; set; }
        public virtual ven_Municipios ven_Municipios { get; set; }
        public virtual world_Localidades world_Localidades { get; set; }
        public virtual world_Localidades world_Localidades1 { get; set; }
        public virtual world_Paises world_Paises { get; set; }
        public virtual world_Profesiones world_Profesiones { get; set; }
        public virtual world_Regiones world_Regiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
