//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas_Sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresas_Sucursales()
        {
            this.Almacenes = new HashSet<Almacenes>();
            this.Clientes = new HashSet<Clientes>();
            this.Empleados = new HashSet<Empleados>();
            this.Grupo_Usuarios = new HashSet<Grupo_Usuarios>();
            this.Licencias = new HashSet<Licencias>();
            this.TiposDescuento = new HashSet<TiposDescuento>();
        }
    
        public short id_Empresas_Sucursales { get; set; }
        public short id_Empresas { get; set; }
        public short id_tiposComercios { get; set; }
        public string Nombre { get; set; }
        public string rif { get; set; }
        public string telefonos { get; set; }
        public short id_world_Regiones { get; set; }
        public long id_world_Localidades { get; set; }
        public short id_world_Idiomas { get; set; }
        public short id_ven_Municipios { get; set; }
        public short id_world_Paises { get; set; }
        public short id_ven_Parroquias { get; set; }
        public System.DateTime FechaActual { get; set; }
        public string Contacto { get; set; }
        public string telefonosContacto { get; set; }
        public string codigoPostal { get; set; }
        public string direccion { get; set; }
        public string ImagenArchivo { get; set; }
        public Nullable<bool> esActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Almacenes> Almacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual TiposComercios TiposComercios { get; set; }
        public virtual ven_Municipios ven_Municipios { get; set; }
        public virtual ven_Parroquias ven_Parroquias { get; set; }
        public virtual world_Idiomas world_Idiomas { get; set; }
        public virtual world_Localidades world_Localidades { get; set; }
        public virtual world_Regiones world_Regiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo_Usuarios> Grupo_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licencias> Licencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposDescuento> TiposDescuento { get; set; }
    }
}
