//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones_Dipositivo_VisorPrecios
    {
        public int id_Estaciones_Dipositivo_VisorPrecios { get; set; }
        public Nullable<int> id_Estaciones { get; set; }
        public Nullable<int> Id_VisorPreciosModelo { get; set; }
        public Nullable<int> id_VisorPreciosVendor { get; set; }
        public bool esVisorPreciosMonitor { get; set; }
        public string Linea1 { get; set; }
        public string Linea2 { get; set; }
        public string Linea3 { get; set; }
        public string Linea4 { get; set; }
        public string PuertoComunicaciones { get; set; }
    }
}
