//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estaciones()
        {
            this.Cajas = new HashSet<Cajas>();
            this.Estaciones_Reportes = new HashSet<Estaciones_Reportes>();
            this.Estaciones_Sesiones = new HashSet<Estaciones_Sesiones>();
        }
    
        public short id_Estaciones { get; set; }
        public short id_Licencias { get; set; }
        public short id_DefTipos_Estacion { get; set; }
        public Nullable<short> id_DefTipos_PedirDatosCliente { get; set; }
        public short id_DefTipos_PrecioPredet { get; set; }
        public Nullable<short> id_DefTipos_DescargaInventario { get; set; }
        public short id_Almacenes { get; set; }
        public bool esActivo { get; set; }
        public bool esimprimirEgreso { get; set; }
        public bool esImprimirFiscal { get; set; }
        public bool esOffline { get; set; }
        public bool esPedirCantidad { get; set; }
        public bool esPreguntarCerrarApp { get; set; }
        public bool esRemoto { get; set; }
        public bool esRequierePassword { get; set; }
        public string IPEstacion { get; set; }
        public string NombreEquipo { get; set; }
        public string NombreEstacion { get; set; }
        public bool esImprimirNConsumo { get; set; }
        public bool esPoseeTeclado { get; set; }
        public bool esPoseeVisorPrecio { get; set; }
        public bool esPoseeVisorPreciosMonitorExtra { get; set; }
        public Nullable<bool> esPoseeGaveta { get; set; }
        public Nullable<bool> esPoseeCaptaHuella { get; set; }
        public Nullable<bool> esPoseePantallaTactil { get; set; }
        public Nullable<bool> esPoseeMouse { get; set; }
        public Nullable<bool> esPoseeLectorPOSBanca { get; set; }
        public Nullable<System.DateTime> FechaUltimaConfiguracion { get; set; }
        public Nullable<bool> esCliente_SolicitarEmail { get; set; }
        public Nullable<bool> esCliente_SolicitarRIF { get; set; }
        public Nullable<bool> esCliente_SolicitarTelefono { get; set; }
        public Nullable<bool> esSolicitarEmpleado { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cajas> Cajas { get; set; }
        public virtual Licencias Licencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estaciones_Reportes> Estaciones_Reportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estaciones_Sesiones> Estaciones_Sesiones { get; set; }
    }
}
