//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones_Dispositivo_Firma
    {
        public short id_Estaciones_Dispositivo_Firma { get; set; }
        public string Bus { get; set; }
        public string BusType { get; set; }
        public string ClassName { get; set; }
        public string Device { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public string SubSystemDeviceName { get; set; }
        public string SubSystemVendor { get; set; }
        public string Vendor { get; set; }
        public string WindowsName { get; set; }
    }
}
