//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones_Reportes
    {
        public short ID_Estacion_Reportes { get; set; }
        public short id_Estaciones { get; set; }
        public string arch_Clientes { get; set; }
        public string arch_Facturas { get; set; }
        public string arch_Servicios { get; set; }
        public string ImpReporte_Clientes { get; set; }
        public string ImpReporte_Facturas { get; set; }
        public string ImpReporte_Movimientos { get; set; }
        public string ImpReporte_Servicios { get; set; }
        public Nullable<byte> nCopias_Clientes { get; set; }
        public Nullable<byte> nCopias_Facturas { get; set; }
        public Nullable<byte> nCopias_Movimientos { get; set; }
        public Nullable<byte> nCopias_Servicios { get; set; }
    
        public virtual Estaciones Estaciones { get; set; }
    }
}
