//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones_Sesiones_Detalle
    {
        public long id_Estaciones_Sesiones_Detalle { get; set; }
        public long id_Estaciones_Sesiones { get; set; }
        public long id_ArchivoAsociado { get; set; }
        public string ArchivoAsociado { get; set; }
        public Nullable<bool> esActualizar { get; set; }
        public Nullable<bool> esAgregar { get; set; }
        public Nullable<bool> esEditar { get; set; }
        public Nullable<bool> esEliminar { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public string ModuloActual { get; set; }
        public string RegistroFinal { get; set; }
        public string RegistroOriginal { get; set; }
    
        public virtual Estaciones_Sesiones Estaciones_Sesiones { get; set; }
    }
}
