//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones_Dispositivo_GavetaDinero
    {
        public short id_Estaciones_Dispositivo_GavetaDinero { get; set; }
        public Nullable<short> id_Estaciones { get; set; }
        public string Comando { get; set; }
        public bool esGavetaDineroFiscal { get; set; }
        public string PuertoComunicaciones { get; set; }
    }
}
