//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones_Dispositivo_Balanza
    {
        public short id_Estaciones_Dispositivo_Balanza { get; set; }
        public Nullable<short> id_DefBalanzaModelo { get; set; }
        public Nullable<short> id_DefBalanza { get; set; }
        public short id_Estacion { get; set; }
        public Nullable<byte> AnchoCodigoArticulo { get; set; }
        public Nullable<byte> AnchoValorPeso { get; set; }
        public string CodigoBalanza { get; set; }
        public Nullable<bool> esLeerCodigo { get; set; }
        public Nullable<bool> esPuertoCOM { get; set; }
        public string NombrePuerto { get; set; }
        public string Parametros { get; set; }
        public Nullable<byte> PosicionFinCodigoArticulo { get; set; }
        public Nullable<byte> PosicionFinPesoDecimal { get; set; }
        public Nullable<byte> PosicionFinPesoEntero { get; set; }
        public Nullable<byte> PosicionIniCodigoArticulo { get; set; }
        public Nullable<byte> PosicionIniPesoDecimal { get; set; }
        public Nullable<byte> PosicionIniPesoEntero { get; set; }
    }
}
