//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Cajas_Cortes = new HashSet<Cajas_Cortes>();
            this.Cajas_Cortes1 = new HashSet<Cajas_Cortes>();
            this.Cajas_Cortes2 = new HashSet<Cajas_Cortes>();
            this.Cajas_Cortes3 = new HashSet<Cajas_Cortes>();
            this.Facturas_Descuentos = new HashSet<Facturas_Descuentos>();
            this.Facturas_Detalle = new HashSet<Facturas_Detalle>();
            this.Facturas_IF = new HashSet<Facturas_IF>();
            this.Facturas_Impuestos = new HashSet<Facturas_Impuestos>();
            this.Facturas_Modificadas = new HashSet<Facturas_Modificadas>();
            this.Facturas_Servicios = new HashSet<Facturas_Servicios>();
            this.Facturas_TiposPago = new HashSet<Facturas_TiposPago>();
        }
    
        public long id_Facturas { get; set; }
        public Nullable<short> id_Cajas { get; set; }
        public Nullable<short> id_Empleados { get; set; }
        public Nullable<long> id_Clientes { get; set; }
        public Nullable<long> id_Cajas_Cortes { get; set; }
        public Nullable<short> id_DefStatusFactura { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime FechaActual { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public string nroFactura { get; set; }
        public string nroFacturaIF { get; set; }
        public string nroControl { get; set; }
    
        public virtual Cajas Cajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cajas_Cortes> Cajas_Cortes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cajas_Cortes> Cajas_Cortes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cajas_Cortes> Cajas_Cortes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cajas_Cortes> Cajas_Cortes3 { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Descuentos> Facturas_Descuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Detalle> Facturas_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_IF> Facturas_IF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Impuestos> Facturas_Impuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Modificadas> Facturas_Modificadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Servicios> Facturas_Servicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_TiposPago> Facturas_TiposPago { get; set; }
    }
}
