//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas_IF
    {
        public long Id_Facturas_IF { get; set; }
        public long Id_Factura { get; set; }
        public System.DateTime FechaIF { get; set; }
        public int NroRef_IF { get; set; }
        public string SerialIF { get; set; }
        public string RIF_IF { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
