//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas_Modificadas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas_Modificadas()
        {
            this.Facturas_Modificadas_IF = new HashSet<Facturas_Modificadas_IF>();
        }
    
        public long id_Facturas_modificadas { get; set; }
        public long id_Estaciones_Sesiones { get; set; }
        public long id_Factura { get; set; }
        public short id_DefTipoModificacion { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaActual { get; set; }
    
        public virtual Estaciones_Sesiones Estaciones_Sesiones { get; set; }
        public virtual Facturas Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Modificadas_IF> Facturas_Modificadas_IF { get; set; }
    }
}
