//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas_Impuestos
    {
        public long id_Facturas_Impuestos { get; set; }
        public long id_Facturas { get; set; }
        public short Id_TiposImpuestos { get; set; }
        public decimal Tasa { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual TiposImpuestos TiposImpuestos { get; set; }
    }
}
