//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modulos()
        {
            this.Usuarios_rolesModulo = new HashSet<Usuarios_rolesModulo>();
        }
    
        public short id_modulos { get; set; }
        public string nombre_archivo { get; set; }
        public string modulo { get; set; }
        public Nullable<short> id_DefTemaModulo { get; set; }
        public Nullable<byte> C_top { get; set; }
        public Nullable<byte> C_left { get; set; }
        public Nullable<byte> topMost { get; set; }
        public Nullable<byte> C_width { get; set; }
        public Nullable<byte> C_height { get; set; }
        public Nullable<byte> startPosition { get; set; }
        public Nullable<byte> modal { get; set; }
        public Nullable<byte> WindowsState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_rolesModulo> Usuarios_rolesModulo { get; set; }
    }
}
