//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_Compuestos
    {
        public long id_Productos_Compuestos { get; set; }
        public long id_Productos { get; set; }
        public short id_UnidadesMedida { get; set; }
        public decimal Cantidad { get; set; }
        public string Descripcion { get; set; }
    }
}
