//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_Calzado
    {
        public long Id_Productos_Calzado { get; set; }
        public long Id_Productos { get; set; }
        public Nullable<bool> esUsaColores { get; set; }
        public Nullable<bool> esUsaTallas { get; set; }
        public Nullable<bool> esCalzado { get; set; }
    }
}
