//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_Farmacia
    {
        public long Id_Productos_Farmacia { get; set; }
        public long Id_Productos { get; set; }
        public Nullable<short> Id_DefTipoRecipeMedico { get; set; }
        public bool esPideRecipeMedico { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    }
}
