//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDescuento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposDescuento()
        {
            this.Facturas_Descuentos = new HashSet<Facturas_Descuentos>();
            this.Facturas_Detalle_Descuentos = new HashSet<Facturas_Detalle_Descuentos>();
        }
    
        public short id_TiposDescuento { get; set; }
        public string Descuento { get; set; }
        public bool esDescuento { get; set; }
        public decimal TasaValor { get; set; }
        public System.DateTime FechaActual { get; set; }
        public bool esValor { get; set; }
        public short id_Empresas_Sucursales { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Empresas_Sucursales Empresas_Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Descuentos> Facturas_Descuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Detalle_Descuentos> Facturas_Detalle_Descuentos { get; set; }
    }
}
