//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposPago()
        {
            this.Cajas = new HashSet<Cajas>();
            this.Clientes = new HashSet<Clientes>();
            this.Facturas_TiposPago = new HashSet<Facturas_TiposPago>();
        }
    
        public short id_TiposPago { get; set; }
        public short id_TiposPago_Doc { get; set; }
        public string tipoPago { get; set; }
        public Nullable<bool> esBonoAlimentacion { get; set; }
        public Nullable<bool> esCredito { get; set; }
        public Nullable<decimal> PorcentajeBanco { get; set; }
        public string ImagenArchivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cajas> Cajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_TiposPago> Facturas_TiposPago { get; set; }
        public virtual TiposPago_Doc TiposPago_Doc { get; set; }
    }
}
