//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_roles
    {
        public short id_Usuarios_roles { get; set; }
        public Nullable<short> id_usuario { get; set; }
        public Nullable<bool> esAccesoremoto { get; set; }
        public Nullable<bool> esAgregar { get; set; }
        public Nullable<bool> esEliminar { get; set; }
        public Nullable<bool> esConsultar { get; set; }
        public Nullable<bool> esModificar { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
