//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_detalle
    {
        public long id_Usuarios_detalle { get; set; }
        public short id_Usuarios { get; set; }
        public short id_DefUsuarioOperacion { get; set; }
        public short id_Modulos { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_UltimoAcceso { get; set; }
        public Nullable<System.DateTime> Fecha_login { get; set; }
        public bool esLogeado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
