//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kss_ERPSucursal_WebControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_rolesModulo
    {
        public short id_usuarios_rolesModulos { get; set; }
        public string control_tag { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public Nullable<bool> esAgregar { get; set; }
        public Nullable<bool> esConsultar { get; set; }
        public Nullable<bool> esEliminar { get; set; }
        public Nullable<bool> esEnabled { get; set; }
        public Nullable<bool> esModificar { get; set; }
        public Nullable<bool> esVisible { get; set; }
        public short id_Modulos { get; set; }
        public short id_usuario { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
